version: '3.8'
services:
  glusterfs:
    image: lulceltech/gluster:latest
    ports:
      - target: 24007 # Gluster Daemon
        published: 24007
        protocol: tcp
        mode: host
      - target: 24008 # Management
        published: 24008
        protocol: tcp
        mode: host
      - target: 49152 # 49152 - 4915* are brick ports, 1 port per brick
        published: 49152
        protocol: tcp
        mode: host
      - target: 49153
        published: 49153
        protocol: tcp
        mode: host
      - target: 49154
        published: 49154
        protocol: tcp
        mode: host
      - target: 49155
        published: 49155
        protocol: tcp
        mode: host
    environment:
      TASK_ID: "{{.Task.Slot}}"
    extra_hosts:
      - "gluster-1:204.48.26.91"
      - "gluster-2:142.93.249.201"
      - "gluster-3:142.93.203.254"
    deploy:
      mode: global
      labels:
        - "service_type=glusterfs"
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    volumes:
      - glusterfs-data:/gluster/bricks/{{.Task.Slot}}

volumes:
  glusterfs-data:

networks:
  glusterfs-network:
    name: glusterfs-network
    driver: overlay
