version: '3.8'
services:
  glusterfs:
    image: lulceltech/gluster:latest
    hostname: "{{.Node.Hostname}}.chgovr.me" # modify the top level domain to your domain, DO NOT TOUCH {{.Node.Hostname}}
    ports:
      - target: 24007 # Gluster Daemon
        published: 24007
        protocol: tcp
        mode: host
      - target: 24008 # Management
        published: 24008
        protocol: tcp
        mode: host
      - target: 49152 # 49152 - 4915* are volume ports, 1 port per volume, add more as needed
        published: 49152
        protocol: tcp
        mode: host
    environment:
      HOST_NAME: "{{.Node.Hostname}}"
    networks:
      - glusterfs-network
    cap_add: # Very important, without this we cannot create volumes
      - ALL
    deploy:
      mode: global
      endpoint_mode: dnsrr
      labels:
        - "service_type=glusterfs"
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    volumes:
      - /data:/gluster/bricks/{{.Task.Slot}}
      - glusterfs-var-lib:/var/lib/glusterd
      - glusterfs-etc:/etc/glusterfs
      - glusterfs-cgroup:/sys/fs/cgroup

volumes:
  glusterfs-var-run:
  glusterfs-var-lib:
  glusterfs-etc:
  glusterfs-cgroup:

networks:
  glusterfs-network:
    name: glusterfs-network
    driver: overlay
